### ISSUE TITLE
Cant open the pipeline

### ISSUE THREAD

**Issue by Akankshazmaze** [taltechmicrofluidics/CP-for-droplet-analysis#1]
It is showing the following error. I tried opening other pipelines, they work just fine. Only this pipeline is showing error. Could you please help me?
Thanks
![image](https://user-images.githubusercontent.com/77427674/104700442-2a0ac280-573a-11eb-8a11-bdd318114548.png)

**Comment by im-sanka** [comment]
Hi, 
It's the DropletDetection pipeline right?
I tried and it's working fine here.
Did you try to use our sample image first?
I think it's the naming part that we set specifically for our naming format.
Maybe try to change that instead?

**Comment by Akankshazmaze** [comment]
Hi
Actually, the Pipeline itself is not loading. I didn't upload any images before adding the pipeline. I'll try again and let you know though.
Anyway, I reassembled the pipeline through the instructions in the supp file of your paper. 
Thanks
Akanksha
