### ISSUE TITLE
[INFO] If this pipeline is used with CP 4.0 or later

### ISSUE THREAD

**Issue by im-sanka** [taltechmicrofluidics/CP-for-droplet-analysis#2]
The alignment method in the align module needs to be adjusted into "Mutual Information" to make it work.

**Comment by Akankshazmaze** [comment]
Sorry if this is a very silly question, but how do I align the module if the pipeline would not open in Cell Profiler? Or if there is another way to do it, could you direct me? I have to warn you, I am a total noob.
Also, I tried opening the module in the older version of the software. It still shows the same error.

**Comment by im-sanka** [comment]
Hi, maybe you can find the detail of this pipeline's usage here: http://www.rsc.org/suppdata/d0/ay/d0ay00031k/d0ay00031k1.pdf

We explain the procedure to use this pipeline from page 5 onwards.

_Best,_
IS

**Comment by Akankshazmaze** [comment]
Thanks! it was most helpful. 
I have another question now, in the Relate Object module, can I add the measurements of the parent object in the export file?

**Comment by im-sanka** [comment]
@Akankshazmaze I am not sure regarding the additional module you ask for. However, in theory, you can combine any modules available in the CP.
